CREATE TABLE customers (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    "name" varchar(255) NOT NULL,
    sender_id varchar(15) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,

    -- Timestamps
    cid bigint NOT NULL,
    ctime timestamp with time zone NOT NULL,
    mid bigint NOT NULL,
    mtime timestamp with time zone NOT NULL
);