CREATE TABLE messages (
    -- PK
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    body varchar(255) NOT NULL,
    num_segments BIGINT,
    "from" varchar(255),
    "to" varchar(255),
    "status" varchar(255),
    "sid" varchar(255),
    is_mms boolean DEFAULT false,
    is_archived boolean DEFAULT false
  
    -- FK
    customer_id BIGINT NOT NULL
    user_id BIGINT NOT NULL

    -- Timestamps
    cid bigint NOT NULL,
    ctime timestamp with time zone NOT NULL,
    mid bigint NOT NULL,
    mtime timestamp with time zone NOT NULL
);